# Cloud Build - Infrastructure Deployment (Pulumi)
#
# Sovereign Orchestration: All infrastructure changes managed via Cloud Build
# Triggered by: Cloud Build Trigger on infra/** changes
#
# Uses dedicated service account: cloud-build-infra@{project}.iam.gserviceaccount.com
# (NOT the default Cloud Build SA per least-privilege principles)
#
# Required substitutions:
#   _ENV: dev, beta, gamma, or prod
#   _PULUMI_BACKEND_URL: gs://expert-ai-pulumi-state

timeout: 1800s # 30 minutes for infra deployments

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY

# Use dedicated SA instead of default Cloud Build SA
serviceAccount: "projects/${PROJECT_ID}/serviceAccounts/cloud-build-infra@${PROJECT_ID}.iam.gserviceaccount.com"

substitutions:
  _ENV: dev
  _PULUMI_BACKEND_URL: gs://expert-ai-pulumi-state

steps:
  # Step 1: Install Pulumi and Python dependencies, then deploy
  - id: "pulumi-deploy"
    name: "python:3.11"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -e

        # Install Pulumi CLI
        curl -fsSL https://get.pulumi.com | bash -s -- --version 3.140.0
        export PATH="/builder/home/.pulumi/bin:$$PATH"

        # Install Python dependencies
        cd infra
        pip install -r requirements.txt

        # Login to GCS backend
        pulumi login ${_PULUMI_BACKEND_URL}

        # Select or create stack
        pulumi stack select ${_ENV} 2>/dev/null || pulumi stack init ${_ENV}

        # Deploy
        if [ "${_ENV}" = "prod" ]; then
          echo "🔒 Production deployment - running preview only"
          pulumi preview --stack ${_ENV}
          echo "⚠️ Production requires manual approval"
        else
          echo "🚀 Deploying to ${_ENV}"
          pulumi up --yes --stack ${_ENV}
        fi

        # Show outputs
        echo "📋 Stack Outputs:"
        pulumi stack output --stack ${_ENV} --json || true
    env:
      - "GOOGLE_CLOUD_PROJECT=$PROJECT_ID"
    secretEnv: ["PULUMI_CONFIG_PASSPHRASE"]

# Available secrets (from root project - shared across all environments)
availableSecrets:
  secretManager:
    - versionName: projects/expert-ai-root/secrets/pulumi-config-passphrase/versions/latest
      env: "PULUMI_CONFIG_PASSPHRASE"
