# Cloud Build configuration for Expert Agent Platform
# This file is triggered by GitHub Actions or directly via gcloud builds submit

substitutions:
  _ENV: "dev"
  _PROJECT_ID: "expert-ai-dev"
  _REGION: "us-central1"
  _SERVICE_NAME: "expert-agent"
  _ARTIFACT_REGISTRY: "us-central1-docker.pkg.dev/expert-ai-root/expert-agent"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
  dynamic_substitutions: true

steps:
  # ============================================
  # Step 1: Install dependencies
  # ============================================
  - id: "install-deps"
    name: "node:20-alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        npm install -g pnpm
        pnpm install --frozen-lockfile

  # ============================================
  # Step 2: Run tests (unit + integration)
  # ============================================
  - id: "run-tests"
    name: "node:20-alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        npm install -g pnpm
        pnpm test:unit
        pnpm test:integration
    env:
      - "VERTEX_AI_MOCK=true"
      - "STRIPE_MOCK=true"
    waitFor: ["install-deps"]

  # ============================================
  # Step 3: Build Next.js application
  # ============================================
  - id: "build-app"
    name: "node:20-alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        npm install -g pnpm
        pnpm build
    env:
      - "NODE_ENV=production"
      - "NEXT_PUBLIC_ENV=${_ENV}"
    waitFor: ["run-tests"]

  # ============================================
  # Step 4: Build Docker image
  # ============================================
  - id: "build-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA}"
      - "-t"
      - "${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${_ENV}-latest"
      - "--build-arg"
      - "ENV=${_ENV}"
      - "."
    waitFor: ["build-app"]

  # ============================================
  # Step 5: Push to Artifact Registry
  # ============================================
  - id: "push-image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}"
    waitFor: ["build-image"]

  # ============================================
  # Step 6: Deploy to Cloud Run
  # ============================================
  - id: "deploy-cloud-run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image=${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA}"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--memory=1Gi"
      - "--cpu=1"
      - "--min-instances=0"
      - "--max-instances=10"
      - "--set-env-vars=NODE_ENV=production,ENV=${_ENV}"
      - "--set-secrets=DATABASE_URL=database-url:latest,GOOGLE_CLIENT_ID=google-client-id:latest,GOOGLE_CLIENT_SECRET=google-client-secret:latest,STRIPE_SECRET_KEY=stripe-secret-key:latest,STRIPE_WEBHOOK_SECRET=stripe-webhook-secret:latest"
      - "--service-account=${_SERVICE_NAME}-sa@${_PROJECT_ID}.iam.gserviceaccount.com"
    waitFor: ["push-image"]

  # ============================================
  # Step 7: Run database migrations
  # ============================================
  - id: "run-migrations"
    name: "node:20-alpine"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        npm install -g pnpm
        pnpm db:migrate
    secretEnv: ["DATABASE_URL"]
    waitFor: ["deploy-cloud-run"]

  # ============================================
  # Step 8: Smoke test
  # ============================================
  - id: "smoke-test"
    name: "gcr.io/cloud-builders/curl"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        # Wait for service to be ready
        sleep 10
        # Get service URL
        SERVICE_URL=$(gcloud run services describe ${_SERVICE_NAME} --region=${_REGION} --format='value(status.url)')
        # Health check
        curl -f "$SERVICE_URL/api/health" || exit 1
        echo "✅ Smoke test passed: $SERVICE_URL"
    waitFor: ["run-migrations"]

availableSecrets:
  secretManager:
    - versionName: projects/${_PROJECT_ID}/secrets/database-url/versions/latest
      env: "DATABASE_URL"

images:
  - "${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${SHORT_SHA}"
  - "${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${_ENV}-latest"

timeout: "1800s" # 30 minutes
